### ISSUE TITLE
Name ideas for the app

### ISSUE THREAD

**Issue by cmnghb** [empirical-org/Synonyms#2]
My idea: keep it simple, keep it fun. "Synonymous" is accurate, fun to say, and simple.

**Comment by heiwanalady** [comment]
WordSyn 
(a little play on Syn/Sin)

**Comment by pxh1432** [comment]
syntastic synonyms 

There seems to be a game called Synonymous: Puzzle Pop Quizzes so I am not sure if you want to stay away from that.
