### ISSUE TITLE
Fix Two Word words

### ISSUE THREAD

**Issue by petergault** [empirical-org/Synonyms#47]
Let’s either: 
(1) remove all two words from the app for now
(2) find a good solution so that we can support two word words where the user is able to use a space. 
For example: a user inputs a word with a space, the system converts this into a word with a dash to check against the word with a dash in the database. The display on the user end is with a space.

**Comment by yordok** [comment]
When the user presses the spacebar, a dash is put in its place instead of a space.  This is allows the compare function to work with two word words without them having to use a dash.
