### ISSUE TITLE
Persistent State - Assign a number to each palayer. 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Synonyms#6]
When players join the room they are given a player number. 
We persist the total number of players. 
The player is shown something like Player #3 at some point on the page, it is clear this is the current player.

**Comment by petergault** [comment]
Assign a name to each player based on an animal: 

https://docs.google.com/a/quill.org/spreadsheets/d/1pMj65X0Eok1WEYjIQxHsQVyX3TT8D0PLfEVazAgAxeM/edit#gid=0

**Comment by cmnghb** [comment]
Persistent room information (and therefore a universal timer for all current players) is still not a thing yet, but I have implemented the animal names thing successfully. I also filtered the list so that it's obvious which one is you.
